default:
  bucket: cumulus-test-sandbox-internal

mvd-tf:
  bucket: mvd-internal

mvd-dev-tf:
  bucket: mvd-internal

jl-tf:
  bucket: jl-test-integration-internal

kk-test-tf:
  bucket: kk-test-internal

lf-test-tf:
  bucket: lf-internal

mth-tf:
  bucket: mth-internal

lpf-tf:
  bucket: lf-internal

bt-tf:
  bucket: bt-internal
