
default:

  # test configuration starts
  test_configs:
    stackName: '{{prefix}}'
    bucket: '{{buckets.internal.name}}'
    DISTRIBUTION_ENDPOINT: '{{api_distribution_url}}'
    esHost: '{{esHost}}'
    streamName: '{{prefix}}-testStream'
    cnmResponseStream: '{{prefix}}-cnmResponseStream'
    AWS_ACCOUNT_ID: '{{AWS_ACCOUNT_ID}}'
    AWS_REGION: us-east-1
    asyncOperationRunnerRole: 'arn:aws:iam::{{AWS_ACCOUNT_ID}}:role/{{prefix}}-lambda-api-gateway'
    sqs_consumer_rate: 300

  # test configuration ends

  cmaDir: '/opt/'
  sandbox_cma_layer: arn:aws:lambda:us-east-1:{{AWS_ACCOUNT_ID}}:layer:Cumulus_Message_Adapter:9
  sit_cma_layer: arn:aws:lambda:us-east-1:{{AWS_ACCOUNT_ID}}:layer:Cumulus_Message_Adapter:2
  cma_layer: '{{sandbox_cma_layer}}'
  prefix: 'test-cumulus-integration'
  prefixNoDash: TestCumulusIntegration
  useNgapPermissionBoundary: true
  shared_data_bucket: cumulus-data-shared
  api_lambda_memory: 756
  iam:
    params:
      - name: ResourcePrefix
        value: '{{prefix}}'
  app:
    params:
      - name: CmrPassword
        value: '{{CMR_PASSWORD}}'
      - name: DockerEmail
        value: '{{DOCKER_EMAIL}}'
      - name: DockerPassword
        value: '{{DOCKER_PASS}}'
      - name: LaunchpadPassphrase
        value: '{{LAUNCHPAD_PASSPHRASE}}'


  vpc:
    vpcId: '{{VPC_ID}}'
    subnets:
      - '{{AWS_SUBNET}}'
    securityGroup: '{{SECURITY_GROUP}}'

  ecs:
    instanceType: t2.medium
    minInstances: 1
    desiredInstances: 1
    maxInstances: 2
    availabilityZone: us-east-1b
    publicIp: false
    restartTasksOnDeploy: true
    docker:
      username: cumulususer
    services:
      EcsTaskHelloWorld:
        image: cumuluss/cumulus-ecs-task:1.3.0
        cpu: 400
        memory: 700
        count: 1
        envs:
          AWS_DEFAULT_REGION:
            function: Fn::Sub
            value: '${AWS::Region}'
        commands:
          - cumulus-ecs-task
          - '--activityArn'
          - function: Ref
            value: EcsTaskHelloWorldActivity
          - '--lambdaArn'
          - function: Ref
            value: HelloWorldLambdaFunction
        alarms:
          TaskCountHigh:
            alarm_description: 'There are more tasks running than the desired'
            comparison_operator: GreaterThanThreshold
            evaluation_periods: 1
            metric: MemoryUtilization
            statistic: SampleCount
            threshold: '{{ecs.services.EcsTaskHelloWorld.count}}'
  activities:
    - name: EcsTaskHelloWorld
    - name: EcsTaskHelloWorldKesCma

  system_bucket: '{{buckets.internal.name}}'

  buckets:
    internal:
      name: cumulus-test-sandbox-internal
      type: internal
    private:
      name: cumulus-test-sandbox-private
      type: private
    protected:
      name: cumulus-test-sandbox-protected
      type: protected
    public:
      name: cumulus-test-sandbox-public
      type: public
    protected-2:
      name: cumulus-test-sandbox-protected-2
      type: protected
    shared:
      name: cumulus-data-shared
      type: shared
    sandbox-dashboard:
      name: cumulus-dashboard-sandbox
      type: shared
    sit-dashboard:
      name: cumulus-dashboard-sit
      type: shared

  cmr:
    username: '{{CMR_USERNAME}}'
    provider: CUMULUS
    clientId: 'cumulus-core-{{prefix}}'
    password: '{{CMR_PASSWORD}}'

  ems:
    provider: CUMULUS

  stepFunctions: !!files [
    'workflows/helloworld.yml',
    'workflows/cnm.yml',
    'workflows/errorsAndRetries.yml',
    'workflows/sips.yml',
    'workflows/ingestGranule.yml',
    'workflows/syncGranule.yml',
    'workflows/browseExample.yml'
  ]

  apiStage: dev
  apiConfigs:
    backend:
      private: true
      port: 8000
    distribution:
      private: true
      port: 7000
      logApiGatewayToCloudWatch: true
  logToSharedDestination: '{{SHARED_LOG_DESTINATION_ARN}}'

  sns:
    reportExecutions:
      subscriptions:
        2ndlambda:
          endpoint:
            function: Fn::GetAtt
            array:
              - SnsS3TestLambdaFunction
              - Arn
          protocol: lambda

  urs_url: https://uat.urs.earthdata.nasa.gov/ #make sure to include the trailing slash

    # if not specified the value of the apigateway backend endpoint is used
    # api_backend_url: https://apigateway-url-to-api-backend/ #make sure to include the trailing slash

    # if not specified the value of the apigateway distribution url is used
    # api_distribution_url: https://apigateway-url-to-distribution-app/ #make sure to include the trailing slash

  deployDistributionApi: true

  # URS users who should have access to the dashboard application.
  users:
    - username: aimeeb
    - username: chuckwondo
    - username: jennyhliu
    - username: jhliu
    - username: jnorton1
    - username: kbaynes
    - username: kkelly
    - username: kakelly2
    - username: kovarik
    - username: lfrederick
    - username: mhuffnagle2
    - username: pquinn1
    - username: menno.vandiermen
    - username: matthewsavoie
    - username: mhsavoie
    - username: mboyd
    - username: jmcampbell


# ------------------------
# CUMULUS team deployments
# ------------------------
cumulus-from-npm:
  prefix: test-npm-integration # used by the integration repo
  prefixNoDash: TestNpmIntegration

cumulus-from-source:
  prefix: test-src-integration # used by the cumulus repo
  prefixNoDash: TestSourceIntegration
  app:
    params:
      - name: CmrPassword
        value: CmrNoPassword
      - name: DockerEmail
        value: '{{DOCKER_EMAIL}}'
      - name: DockerPassword
        value: '{{DOCKER_PASS}}'
      - name: LaunchpadPassphrase
        value: '{{LAUNCHPAD_PASSPHRASE}}'
  ems:
    provider: CUMULUS
    host: fs1.ems.eosdis.nasa.gov
    path: tmpNat
    username: cumulus
    dataSource: UAT
    submitReport: true
  cmr:
    oauthProvider: launchpad
    username: CmrUserNotUsed
    password: CmrPasswordNotUsed
  launchpad:
    api: 'https://api.launchpad.nasa.gov/icam/api/sm/v1'
    passphrase: '{{LAUNCHPAD_PASSPHRASE}}'
  oauth:
    provider: launchpad
    userGroup: GSFC-Cumulus-Dev

cumulus-from-pr:
  prefix: test-pr-integration # used by the PR
  prefixNoDash: TestPrIntegration

cumulus-nightly:
  prefix: nightly # used by the nightly cron job
  prefixNoDash: Nightly

cumulus-sit:
  prefix: cumulus-sit
  prefixNoDash: cumulusSit

  buckets:
    internal:
      name: cumulus-sit-internal
      type: internal
    private:
      name: cumulus-sit-private
      type: private
    protected:
      name: cumulus-sit-protected
      type: protected
    public:
      name: cumulus-sit-public
      type: public
    protected-2:
      name: cumulus-sit-protected
      type: protected
  cma_layer: '{{sit_cma_layer}}'

# -------------------------------
# CUMULUS individual deployments.
# -------------------------------

jc-sit:
  prefix: jc-sit
  prefixNoDash: jcSit
  cma_layer: '{{SIT_CMA_LAYER}}'
  buckets:
    internal:
      name: jc-sit-internal
      type: internal
    private:
      name: jc-sit-private
      type: private
    protected:
      name: cumulus-sit-protected
      type: protected
    public:
      name: cumulus-sit-public
      type: public
    protected-2:
      name: cumulus-sit-protected
      type: protected
    dashboard:
      name: jc-sit-dashboard
      type: shared

jk-sit:
  stackName: jk-sit
  stackNameNoDash: jkSit
  buckets:
    internal:
      name: jk-sit-internal
      type: internal
    private:
      name: jk-sit-private
      type: private
    protected:
      name: cumulus-sit-protected
      type: protected
    public:
      name: cumulus-sit-public
      type: public
    protected-2:
      name: cumulus-sit-protected
      type: protected
    dashboard:
      name: jk-sit-dashboard
      type: shared
  cma_layer: '{{sit_cma_layer}}'

aimee:
  prefix: aimee
  prefixNoDash: aimee

lf:
  prefix: lf-cumulus
  prefixNoDash: lfCumulus

  es:
    name: estest

  # api_distribution_url: '{{API_DISTRIBUTION_URL}}'

  buckets:
    internal:
      name: lf-internal
      type: internal
    private:
      name: lf-private
      type: private
    protected:
      name: lf-protected
      type: protected
    public:
      name: lf-cumulus-public
      type: public
    protected-2:
      name: lf-protected-2
      type: protected

lf-test-2:
  prefix: lf-test-2
  prefixNoDash: lfTest2

  buckets:
    internal:
      name: lf-internal
      type: internal
    private:
      name: lf-private
      type: private
    protected:
      name: lf-protected
      type: protected
    public:
      name: lf-cumulus-public
      type: public
    protected-2:
      name: lf-protected-2
      type: protected

lf-int-test:
  prefix: lf-int-test
  prefixNoDash: lfIntTest

  buckets:
    internal:
      name: lf-internal
      type: internal
    private:
      name: lf-private
      type: private
    protected:
      name: lf-protected
      type: protected
    public:
      name: lf-cumulus-public
      type: public
    protected-2:
      name: lf-protected-2
      type: protected

lf-sit:
  prefix: lf-sit
  prefixNoDash: lfSit

  buckets:
    internal:
      name: lf-sit-internal
      type: internal
    private:
      name: lf-sit-private
      type: private
    protected:
      name: lf-sit-protected
      type: protected
    public:
      name: lf-sit-public
      type: public
    protected-2:
      name: lf-sit-protected
      type: protected
  cma_layer: '{{sit_cma_layer}}'

kk:
  prefix: kk-test
  prefixNoDash: KkTest
  esHost: https://search-kk-test-es5-bk24w6blilunzp4fc4ma3xwtqu.us-east-1.es.amazonaws.com
  system_bucket: '{{prefix}}-internal'
  buckets:
    internal:
      name: '{{prefix}}-internal'
      type: internal
    private:
      name: '{{prefix}}-private'
      type: private
    protected:
      name: '{{prefix}}-protected'
      type: protected
    public:
      name: '{{prefix}}-public'
      type: public
  ecs:
    ssh: true
    keyPairName: kakelly2-cumulus-sandbox
  cmr:
    oauthProvider: launchpad
    username: CmrUserNotUsed
    password: CmrPasswordNotUsed
  launchpad:
    api: 'https://api.launchpad.nasa.gov/icam/api/sm/v1'
    passphrase: '{{LAUNCHPAD_PASSPHRASE}}'
  oauth:
    provider: launchpad
    userGroup: GSFC-Cumulus-Dev

kk-int-test:
  prefix: kk-int-test
  prefixNoDash: KkIntTest

mth:
  prefix: mth
  prefixNoDash: Mth
  useWorkflowLambdaVersions: false
  buckets:
    internal:
      name: '{{prefix}}-internal'
      type: internal
    private:
      name: '{{prefix}}-private'
      type: private
    protected:
      name: '{{prefix}}-protected'
      type: protected
    protected-2:
      name: '{{prefix}}-protected'
      type: protected
    public:
      name: '{{prefix}}-public'
      type: public
  ecs:
    # amiid: ami-0bc08634af113cccb
    maxInstances: 3
    ssh: true
    keyPairName: mhuffnag
    # efs:
    #   mount: /efs

jl:
  prefix: jl-test-integration
  prefixNoDash: JlTestIntegration
  useWorkflowLambdaVersions: false
  buckets:
    private:
      name: jl-test-integration-private
      type: private
    protected:
      name: jl-test-integration-protected
      type: protected
    public:
      name: jl-test-integration-public
      type: public
    protected-2:
      name: jl-test-integration-protected-2
      type: protected
    shared-2:
      name: rvl-internal
      type: shared
  app:
    params:
      - name: CmrPassword
        value: CmrNoPassword
      - name: DockerEmail
        value: '{{DOCKER_EMAIL}}'
      - name: DockerPassword
        value: '{{DOCKER_PASS}}'
      - name: LaunchpadPassphrase
        value: '{{LAUNCHPAD_PASSPHRASE}}'
  ecs:
    ssh: true
    keyPairName: jl
  ems:
    provider: CUMULUS
    host: fs1.ems.eosdis.nasa.gov
    path: tmpNat
    username: cumulus
    dataSource: UAT
    submitReport: true
    retentionInDays: 20
  cmr:
    oauthProvider: launchpad
    username: CmrUserNotUsed
    password: CmrPasswordNotUsed
  launchpad:
    api: 'https://api.launchpad.nasa.gov/icam/api/sm/v1'
    passphrase: '{{LAUNCHPAD_PASSPHRASE}}'
  oauth:
    provider: launchpad
    userGroup: GSFC-Cumulus-Dev
  samlConfig:
    entityID: 'https://cumulus-sandbox.earthdata.nasa.gov/jl-test-integration'
    assertionConsumerService: 'https://5hlnofihz8.execute-api.us-east-1.amazonaws.com:8000/dev/saml/auth'
    idpLogin: 'https://auth.launchpad-sbx.nasa.gov/affwebservices/public/saml2sso'
    launchpadMetadataPath: 's3://{{buckets.internal.name}}/{{prefix}}/launchpad/launchpad-sbx-metadata.xml'

jl-cumulus:
  prefix: jl-cumulus
  prefixNoDash: jlCumulus

gitc:
  prefix: {{PREFIX}}
  prefixNoDash: {{prefixNoDash}}

  iams:
    ecsRoleArn: 'arn:aws:iam::{{AWS_ACCOUNT_ID}}:role/{{PREFIX}}-ecs'
    lambdaApiGatewayRoleArn: 'arn:aws:iam::{{AWS_ACCOUNT_ID}}:role/{{PREFIX}}-lambda-api-gateway'
    lambdaProcessingRoleArn: 'arn:aws:iam::{{AWS_ACCOUNT_ID}}:role/{{PREFIX}}-lambda-processing'
    stepRoleArn: 'arn:aws:iam::{{AWS_ACCOUNT_ID}}:role/{{PREFIX}}-steprole'
    instanceProfile: 'arn:aws:iam::{{AWS_ACCOUNT_ID}}:instance-profile/{{PREFIX}}-ecs'
    distributionRoleArn: 'arn:aws:iam::{{AWS_ACCOUNT_ID}}:role/{{PREFIX}}-distribution-api-lambda'

  buckets:
    internal:
      name: '{{PREFIX}}-internal'
      type: internal
    private:
      name: '{{PREFIX}}-private'
      type: private
    protected:
      name: '{{PREFIX}}-protected'
      type: protected
    public:
      name: '{{PREFIX}}-public'
      type: public
    protected-2:
      name: '{{PREFIX}}-protected-2'
      type: protected
    shared:
      name: '{{PREFIX}}-data-shared'
      type: shared
  api_distribution_url: '{{API_DISTRIBUTION_URL}}'
  system_bucket: '{{buckets.internal.name}}'

  users:
    - username: '{{EARTHDATA_LOGIN_USERNAME}}'

  AutoScalingPolicyConfiguration:
  GranulesTable:
    enableAutoScaling: false
  FilesTable:
    enableAutoScaling: false

mvd:
  prefix: mvd
  prefixNoDash: mvd
  useWorkflowLambdaVersions: false
  buckets:
    internal:
      name: '{{prefix}}-internal'
      type: internal
  bucket: '{{prefix}}-internal'

mvd-dev:
  prefix: mvd-dev
  prefixNoDash: mvdDev
  buckets:
    internal:
      name: 'mvd-internal'
      type: internal
  bucket: 'mvd-internal'

jc:
  prefix: jc
  prefixNoDash: jc
  # ecs:
  #  services:
  #    EcsTaskHelloWorld:
  #      image: '{{ECR_TESTING_IMAGE_ARN}}'
  #      cpu: 400
  #      memory: 700
  #      count: 1
  #      envs:
  #        AWS_DEFAULT_REGION:
  #          function: Fn::Sub
  #          value: '${AWS::Region}'
  #      commands:
  #        - cumulus-ecs-task
  #        - '--activityArn'
  #        - function: Ref
  #          value: EcsTaskHelloWorldActivity
  #        - '--lambdaArn'
  #        - function: Ref
  #          value: HelloWorldLambdaFunction
  #  docker:
  #    username: cumulususer
  #    registry: ecr

mhs:
  prefix: mhs
  prefixNoDash: mhs
  ecs:
    ssh: true
    keyPairName: mhs
  api_distribution_url:

mhs3:
  prefix: mhs3
  prefixNoDash: mhs3
  buckets:
    internal:
      name: mhs3-internal
      type: internal
    private:
      name: mhs3-private
      type: private
    protected:
      name: mhs3-protected
      type: protected
    public:
      name: mhs3-public
      type: public
    protected-2:
      name: mhs3-protected-2
      type: protected
    shared:
      name: cumulus-data-shared
      type: shared
  system_bucket: mhs3-internal
  api_distribution_url:
  ecs:
    ssh: true
    keyPairName: mhs
  apiConfigs:
    backend:
      private: true
      port: 8003
    distribution:
      private: true
      port: 7003
      logApiGatewayToCloudWatch: true
  logToSharedDestination: '{{SHARED_LOG_DESTINATION_ARN}}'

mhs4:
  prefix: mhs4
  prefixNoDash: mhs4
  buckets:
    internal:
      name: mhs4-internal
      type: internal
    private:
      name: mhs4-private
      type: private
    protected:
      name: mhs4-protected
      type: protected
    public:
      name: mhs4-public
      type: public
    protected-2:
      name: mhs4-protected-2
      type: protected
    shared:
      name: cumulus-data-shared
      type: shared
  system_bucket: mhs4-internal
  api_distribution_url:
  ecs:
    ssh: true
    keyPairName: mhs
  launchpad:
    api: 'https://api.launchpad.nasa.gov/icam/api/sm/v1'
    passphrase: '{{LAUNCHPAD_PASSPHRASE}}'
  apiConfigs:
    backend:
      private: true
      port: 8004
    distribution:
      private: true
      port: 7014
      logApiGatewayToCloudWatch: true
  logToSharedDestination: '{{SHARED_LOG_DESTINATION_ARN}}'
  cmr:
    oauthProvider: launchpad
    username: CmrUserNotUsed
    password: CmrPasswordNotUsed
  oauth:
    provider: launchpad
    userGroup: GSFC-Cumulus-Dev
  # oauth:
  #   provider: earthdatalogin
  #   userGroup: n/a
  samlConfig:
    entityID: 'https://u8ne7bgicd.execute-api.us-east-1.amazonaws.com:8004/dev/'
    assertionConsumerService: 'https://u8ne7bgicd.execute-api.us-east-1.amazonaws.com:8004/dev/saml/auth'
    idpLogin: 'https://auth.launchpad-sbx.nasa.gov/affwebservices/public/saml2sso'
    launchpadMetadataPath: 's3://{{buckets.internal.name}}/{{prefix}}/launchpad/launchpad-sbx-metadata.xml'
  useWorkflowLambdaVersions: true

mhs2:
  prefix: mhs2
  prefixNoDash: mhs2
  buckets:
    internal:
      name: mhs2-internal
      type: internal
    private:
      name: mhs2-private
      type: private
    protected:
      name: mhs2-protected
      type: protected
    public:
      name: mhs2-public
      type: public
    protected-2:
      name: mhs2-protected-2
      type: protected
    dashboard:
      name: mhs2-dashboard
      type: protected
    shared:
      name: cumulus-data-shared
      type: shared
  system_bucket: mhs2-internal
  api_distribution_url:
  ecs:
    ssh: true
    keyPairName: mhs-sit
  apiConfigs:
    backend:
      private: true
      port: 8022
    distribution:
      private: true
      port: 7022
      logApiGatewayToCloudWatch: true
  logToSharedDestination: '{{SHARED_LOG_DESTINATION_ARN}}'
  cma_layer: '{{sit_cma_layer}}'

jk:
  useWorkflowLambdaVersions: false
  prefix: jk
  prefixNoDash: jk
  ecs:
    ssh: true
    keyPairName: jk

jk2:
  useWorkflowLambdaVersions: false
  prefix: jk2
  prefixNoDash: jk2

jk-tf:
  stackName: jk-tf
  useWorkflowLambdaVersions: false
  prefix: jk-tf
  prefixNoDash: jk-tf

jk3:
  stackName: jk3
  stackNameNoDash: jk3
  ecs:
    ssh: true
    keyPairName: jk
  prefix: jk3
  prefixNoDash: jk3

mboyd-test:
  prefix: mboyd-test
  prefixNoDash: mboydTest

  es:
    volumeSize: 10

  ecs:
    ssh: true
    keyPairName: mboyd

mboyd-int:
  prefix: mboyd-int
  prefixNoDash: mboydInt
  ecs:
    ssh: true
    keyPairName: mboyd

chuckulus:
  prefix: chuckulus
  prefixNoDash: chuckulus

chuckulus-ci:
  prefix: chuckulus-ci
  prefixNoDash: chuckulusCI

pq:
  prefix: pq
  prefixNoDash: pq

bt:
  prefix: bt
  prefixNoDash: bt
  logToSharedDestination: '{{SHARED_LOG_DESTINATION_ARN}}'
  users:
    - username: brian.tennity

bt-sit:
  prefix: bt-sit
  prefixNoDash: btSit
  cma_layer: '{{sit_cma_layer}}'
  buckets:
    internal:
      name: bt-sit-internal
      type: internal
    private:
      name: bt-sit-private
      type: private
    protected:
      name: cumulus-sit-protected
      type: protected
    public:
      name: cumulus-sit-public
      type: public
    protected-2:
      name: cumulus-sit-protected
      type: protected
    dashboard:
      name: bt-sit-dashboard
      type: shared

